[project]
name = "terminal-cook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-allrecipes>=1.1.0",
    "rich>=14.0.0",
]
